identities:
- name: gcp
  gcp:
    encodedServiceAccountKey: $AGENT_ENCODED_KEY
# Metric names should match verbatim the identifiers created
# during pricing setup.
metrics:
- name: instance_time
  type: int
  endpoints:
  - name: on_disk
  - name: servicecontrol
  passthrough: {}
endpoints:
- name: on_disk
  disk:
    reportDir: /var/lib/ubbagent/reports
    expireSeconds: 3600
- name: servicecontrol
  servicecontrol:
    identity: gcp
    # The service name is unique to your application and will be
    # provided during onboarding.
    serviceName: TODO.my-application.mp-my-company.appspot.com
    consumerId: $AGENT_CONSUMER_ID
sources:
- name: instance_time_heartbeat
  heartbeat:
    metric: instance_time
    intervalSeconds: 60
    value:
      int64Value: 60
