apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/elotl/kip/deploy/manifests/kip/base?ref=vilmos-kustomize-naming
namespace: ${namespace}
namePrefix: ${name}-
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: provider
  path: patch-provider-statefulset.yaml
- target:
    version: v1
    kind: Secret
    name: network-agent
  path: patch-network-agent-secret.yaml
- target:
    version: v1
    kind: PersistentVolumeClaim
    name: provider-data
  path: patch-provider-persistent-volume-claim.yaml
images:
- name: elotl/kip
  newName: ${imageKipProviderRepo}
  newTag: ${imageKipProviderTag}
- name: elotl/init-cert
  newName: ${imageInitCertRepo}
  newTag: ${imageInitCertTag}
- name: k8s.gcr.io/kube-proxy
  newName: ${imageKubeProxyRepo}
  newTag: ${imageKubeProxyTag}
- name: gcr.io/elotl-kip/image-cache-controller
  newName: ${imageImageCacheControllerRepo}
  newTag: ${imageImageCacheControllerTag}
- name: elotl/ubbagent
  newName: ${imageUbbAgentRepo}
  newTag: ${imageUbbAgentTag}
configMapGenerator:
- name: config
  files:
  - provider.yaml
  behavior: merge
- name: ubbagent-config
  files:
  - ubbagent-config.yaml
