application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  deployerImage:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  imageKipProvider:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageKipProviderRepo
            after: imageKipProviderTag
  imageInitCert:
    type: string
    default: $REGISTRY/init-cert:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageInitCertRepo
            after: imageInitCertTag
  imageKubeProxy:
    type: string
    default: $REGISTRY/kube-proxy:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageKubeProxyRepo
            after: imageKubeProxyTag
  imageImageCacheController:
    type: string
    default: $REGISTRY/image-cache-controller:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageImageCacheControllerRepo
            after: imageImageCacheControllerTag
  imageUbbagent:
    type: string
    default: $REGISTRY/ubbagent:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageUbbAgentRepo
            after: imageUbbAgentTag
  kipProviderReplicas:
    title: Number of Kip server replicas
    type: integer
    default: 1
    minimum: 1
    maximum: 64
  googleApplicationCredentials:
    title: GCE service account JSON
    description: A GCE service account JSON that Kip will use to run API requests to create cloud instances in GCE. By default, Kip will use the https://www.googleapis.com/auth/monitoring scope from the VM instance where it runs, so no GCE service account needs to be configured.
    type: string
    default: ""
    x-google-marketplace:
      type: MASKED_FIELD
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  istioEnabled:
    type: boolean
    x-google-marketplace:
      type: ISTIO_ENABLED
  ingressAvailable:
    type: boolean
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  kipServiceAccountName:
    type: string
    title: Service account used by Kip
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups:
              - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
              - authorization.k8s.io
              resources:
                - localsubjectaccessreviews
                - subjectaccessreviews
              verbs:
                - create
            - apiGroups:
              - ""
              resources:
                - services
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - ""
              resources:
                - nodes
              verbs:
                - create
                - get
                - list
                - watch
            - apiGroups:
              - ""
              resources:
                - nodes/status
              verbs:
                - patch
                - update
            - apiGroups:
              - ""
              resources:
                - nodes
              verbs:
                - patch
                - update
            - apiGroups:
              - ""
              resources:
                - events
              verbs:
                - create
                - patch
                - update
            - apiGroups:
              - ""
              resources:
                - pods
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - ""
              resources:
                - pods
              verbs:
                - create
                - delete
            - apiGroups:
              - ""
              resources:
                - pods/status
              verbs:
                - patch
                - update
            - apiGroups:
              - ""
              resources:
                - pods/eviction
              verbs:
                - create
            - apiGroups:
              - ""
              resources:
                - configmaps
                - secrets
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - ""
              resources:
                - persistentvolumeclaims
                - persistentvolumes
              verbs:
                - get
            - apiGroups:
              - ""
              resources:
                - endpoints
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - certificates.k8s.io
              resourceNames:
                - kubernetes.io/kubelet-serving
              resources:
                - signers
              verbs:
                - approve
            - apiGroups:
              - certificates.k8s.io
              resources:
                - certificatesigningrequests
              verbs:
                - create
                - get
                - list
                - watch
            - apiGroups:
              - certificates.k8s.io
              resources:
                - certificatesigningrequests/approval
              verbs:
                - update
            - apiGroups:
              - coordination.k8s.io
              resources:
                - leases
              verbs:
                - create
                - delete
                - get
                - patch
                - update
            - apiGroups:
              - storage.k8s.io
              resources:
                - volumeattachments
              verbs:
                - get
            - apiGroups:
              - ""
              resources:
                - persistentvolumeclaims/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
              - ""
              resources:
                - serviceaccounts/token
              verbs:
                - create
            - apiGroups:
              - storage.k8s.io
              resources:
                - csidrivers
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - storage.k8s.io
              resources:
                - csinodes
              verbs:
                - create
                - delete
                - get
                - patch
                - update
            - apiGroups:
              - node.k8s.io
              resources:
                - runtimeclasses
              verbs:
                - get
                - list
                - watch
            - apiGroups:
              - kip.elotl.co
              resources:
                - cells
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - deletecollection
                - patch
                - update
            - apiGroups:
              - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
                - list
                - watch
                - create
                - delete
                - deletecollection
                - patch
                - update
  kipNetworkAgentServiceAccountName:
    type: string
    title: Service account used by Kip Network Agent
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups:
              - ""
              resources:
                - namespaces
                - pods
                - services
                - nodes
                - endpoints
              verbs:
                - list
                - get
                - watch
            - apiGroups:
              - "networking.k8s.io"
              resources:
                - networkpolicies
              verbs:
                - list
                - get
                - watch
            - apiGroups:
              - extensions
              resources:
                - networkpolicies
              verbs:
                - get
                - list
                - watch
required:
- name
- namespace
- deployerImage
- imageKipProvider
- imageInitCert
- imageKubeProxy
- imageImageCacheController
- imageUbbagent
- kipProviderReplicas
- googleApplicationCredentials
- reportingSecret
#form:
#- widget: help
#  description: My arbitrary <i>description</i>
x-google-marketplace:
  clusterConstraints:
    gcp:
      nodes:
        requiredOauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
    resources:
    - replicas: 1
      requests:
        cpu: 1
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
    istio:
      type: OPTIONAL
